const protectedPostConfig = {
  title: "Postagens",
  descriptionUpdate: "Atualize sua postagem",
  description: "Gerencie suas postagens",
  delete: "Excluir",
  edit: "Editar",
  update: "Atualizar",
  questionDelete: "Tem certeza de que deseja excluir esta postagem?",
  warning: "Essa ação não pode ser desfeita.",
  cancel: "Cancelar",
  confirm: "Confirmar",
  tableHeader: ["Postagem", "Data", "Ação"],
  updatePost: "Atualizar postagem",
  newPost: "Nova postagem",
  successDelete: "Postagem excluída.",
  successCreate: "Postagem criada.",
  successUpdate: "Postagem atualizada.",
  errorCreate: "Não foi possível criar a postagem.",
  errorDelete: "Não foi possível excluir a postagem.",
  errorUpdate: "Não foi possível atualizar a postagem.",
  author: "Autor(a)",
  pleaseWait: "Por favor, aguarde...",
  untitled: "Sem título",
};

export default protectedPostConfig;
