const protectedEditorConfig = {
  generalTitle: "Informação Geral",
  generalDescription: "Atualize as informações da sua postagem",
  title: "Editar",
  slug: "Slug",
  generateSlug: "Gerar Slug",
  description: "Atualize a descrição do sua postagem",
  formTitle: "Título",
  formSlug: "Slug",
  categoryTitle: "Categoria",
  categoryDescription: "Escolha uma categoria para da sua postagem",
  shortDescriptionTitle: "Descrição curta",
  shortDescriptionDescription: "Adicione uma descrição curta da sua postagem",
  mainContentTitle: "Conteúdo Principal",
  mainContentDescription:
    "Upload de imagens com arrastar e soltar.",
  formImage: "Imagem",
  formImageNote: "Somente arquivos JPG, PNG e GIF são permitidos",
  formImageSize: "O tamanho do arquivo não pode exceder 6 MB.",
  coverImageTitle: "Imagem de capa",
  formCoverImageUploadFile: "Enviar um arquivo",
  coverImageDescription: "Você pode fazer upload de uma imagem de capa.",
  galleryImageTitle: "Imagens da galeria",
  galleryImageDescription: "Você pode fazer upload de até ",
  submit: "Atualizar",
  cancel: "Cancelar",
  cofirm: "Confirmar",
  placeHolderTitle: "Forneça um título para a postagem",
  placeholderSlug: "Forneça um slug para a postagem",
  placeholderImage: "Imagem URL",
  deleteImage: "Excluir imagem",
  errorMessagesDeleteImage: "Erro ao excluir imagem",
  errorMessageImageUpload: "Erro ao carregar a imagem",
  successMessagesDeleteImage: "Imagem excluída",
  successMessageImageUpload: "Imagem enviada",
  placeholderDescription:
    "Forneça uma breve descrição da postagem",
  placeholderCategory: "por favor, escolha uma categoria",
  placeholderContent: "Digite aqui o conteúdo da postagem",
  defaultCategoryId: "4db30a13-2797-4c7d-a0ce-e0c127287a39", // Science
  successMessage: "Sua postagem foi atualizada",
  errorMessage: "Erro ao atualizar sua postagem",
  chooseFile: "Fazer upload de arquivos",
  thumbnail: "Thumbnail",
  coverPhoto: "Foto de capa",
  uploadDescription: "PNG, JPG, GIF até 10 MB",
  deleteImageQuestion: "Tem certeza de que deseja apagar esta imagem?",
  deleteImageDescription: "Essa ação não pode ser desfeita.",
};

export default protectedEditorConfig;
