const protectedProfileConfig = {
  primaryTitle: "Informações pessoais",
  primarySubTitle: "Atualize suas informações pessoais.",
  secondaryTitle: "Informação do usuário",
  secondarySubTitle: "Atualize suas informações de usuário",
  formImageNote: "Somente arquivos JPG e PNG são permitidos. 5 MB no máximo.",
  successMessageImageUpload: "Sua imagem foi carregada com sucesso.",
  errorMessageImageUpload: "Não foi possível enviar sua imagem.",
  name: "Nome completo",
  firstName: "Primeiro nome",
  firstNamePlaceholder: "Seu primeiro nome",
  lastName: "Sobrenome",
  lastNamePlaceholder: "Seu último Nome",
  userName: "Nome de usuário",
  userNamePlaceholder: "Seu nome de usuário",
  email: "E-mail",
  emailPlaceholder: "Seu email",
  website: "Website",
  websitePlaceholder: "https://your-website.com",
  update: "Atualizar perfil",
  changeAvatar: "Mudar Avatar",
  uploadNote: "JPG, GIF ou PNG. Máximo de 5 MB.",
  pleaseWait: "Por favor, aguarde...",
  successMessage: "Seu perfil foi atualizado.",
  errorMessage: "Ocorreu um erro ao atualizar seu perfil.",
};

export default protectedProfileConfig;
