import { DiagramSchema } from "beautiful-react-diagrams/@types/DiagramSchema";
import { navigate } from "../../actions/navigate";

const CustomRender = ({ id, content }: { id: string; content: string }) => (
  <div className="flex h-[2rem] w-[5rem] flex-row items-center justify-around rounded-md bg-colabDarkGreen hover:bg-colabPurple">
    {content}
    <span
      className="material-symbols-outlined pointer"
      onClick={() => navigate({ id })}
    >
      zoom_in
    </span>
  </div>
);

export const diagram: unknown = {
  nodes: [
    { id: "root", content: "Perspectivas", coordinates: [5, 10] },
    { id: "1", content: "Identidade da criança", coordinates: [5, 100] },
    { id: "2", content: "Maturidade da criança", coordinates: [5, 400] },
    { id: "3", content: "Apoiar a escolha", coordinates: [5, 700] },
    { id: "4", content: "Conteúdo Informativo", coordinates: [5, 1000] },
    { id: "5", content: "Conteúdos Extremados", coordinates: [5, 1300] },
    {
      id: "01-1I",
      content: "01-1I",
      coordinates: [10, 190],
      render: CustomRender,
    },
    {
      id: "05-1R",
      content: "05-1R",
      coordinates: [110, 190],
      render: CustomRender,
    },
    {
      id: "07-1I",
      content: "07-1I",
      coordinates: [210, 190],
      render: CustomRender,
    },
    {
      id: "15-1R",
      content: "15-1R",
      coordinates: [10, 230],
      render: CustomRender,
    },
    {
      id: "18-1R",
      content: "18-1R",
      coordinates: [110, 230],
      render: CustomRender,
    },
    {
      id: "19-1P",
      content: "19-1P",
      coordinates: [210, 230],
      render: CustomRender,
    },
    {
      id: "23-1R",
      content: "23-1R",
      coordinates: [10, 270],
      render: CustomRender,
    },
    {
      id: "25-1R",
      content: "25-1R",
      coordinates: [110, 270],
      render: CustomRender,
    },
    {
      id: "27-1R",
      content: "27-1R",
      coordinates: [210, 270],
      render: CustomRender,
    },
    {
      id: "29-1R",
      content: "29-1R",
      coordinates: [10, 310],
      render: CustomRender,
    },
    {
      id: "30-1P",
      content: "30-1P",
      coordinates: [110, 310],
      render: CustomRender,
    },
    {
      id: "33-1R",
      content: "33-1R",
      coordinates: [210, 310],
      render: CustomRender,
    },
    {
      id: "38-1R",
      content: "38-1R",
      coordinates: [10, 350],
      render: CustomRender,
    },
    {
      id: "39-1I",
      content: "39-1I",
      coordinates: [110, 350],
      render: CustomRender,
    },
    {
      id: "44-1P",
      content: "44-1P",
      coordinates: [210, 350],
      render: CustomRender,
    },
    {
      id: "02-2I",
      content: "02-2I",
      coordinates: [10, 500],
      render: CustomRender,
    },
    {
      id: "12-2R",
      content: "12-2R",
      coordinates: [110, 500],
      render: CustomRender,
    },
    {
      id: "13-2I",
      content: "13-2I",
      coordinates: [210, 500],
      render: CustomRender,
    },
    {
      id: "14-2P",
      content: "14-2P",
      coordinates: [10, 540],
      render: CustomRender,
    },
    {
      id: "20-2R",
      content: "20-2R",
      coordinates: [110, 540],
      render: CustomRender,
    },
    {
      id: "24-2R",
      content: "24-2R",
      coordinates: [210, 540],
      render: CustomRender,
    },
    {
      id: "28-2R",
      content: "28-2R",
      coordinates: [10, 580],
      render: CustomRender,
    },
    {
      id: "31-2R",
      content: "31-2R",
      coordinates: [110, 580],
      render: CustomRender,
    },
    {
      id: "50-2I",
      content: "50-2I",
      coordinates: [210, 580],
      render: CustomRender,
    },
    {
      id: "08-3I",
      content: "08-3I",
      coordinates: [10, 800],
      render: CustomRender,
    },
    {
      id: "16-3D",
      content: "16-3D",
      coordinates: [110, 800],
      render: CustomRender,
    },
    {
      id: "17-3D",
      content: "17-3D",
      coordinates: [210, 800],
      render: CustomRender,
    },
    {
      id: "43-3P",
      content: "43-3P",
      coordinates: [10, 840],
      render: CustomRender,
    },
    {
      id: "46-3P",
      content: "46-3P",
      coordinates: [110, 840],
      render: CustomRender,
    },
    {
      id: "47-3R",
      content: "47-3R",
      coordinates: [210, 840],
      render: CustomRender,
    },
    {
      id: "48-3I",
      content: "48-3I",
      coordinates: [10, 880],
      render: CustomRender,
    },
    {
      id: "03-4R",
      content: "03-4R",
      coordinates: [10, 1100],
      render: CustomRender,
    },
    {
      id: "04-4R",
      content: "04-4R",
      coordinates: [110, 1100],
      render: CustomRender,
    },
    {
      id: "10-4I",
      content: "10-4I",
      coordinates: [210, 1100],
      render: CustomRender,
    },
    {
      id: "11-4R",
      content: "11-4R",
      coordinates: [10, 1140],
      render: CustomRender,
    },
    {
      id: "21-4I",
      content: "21-4I",
      coordinates: [110, 1140],
      render: CustomRender,
    },
    {
      id: "22-4D",
      content: "22-4D",
      coordinates: [210, 1140],
      render: CustomRender,
    },
    {
      id: "34-4D",
      content: "34-4D",
      coordinates: [10, 1180],
      render: CustomRender,
    },
    {
      id: "35-4D",
      content: "35-4D",
      coordinates: [110, 1180],
      render: CustomRender,
    },
    {
      id: "40-4P",
      content: "40-4P",
      coordinates: [210, 1180],
      render: CustomRender,
    },
    {
      id: "41-4D",
      content: "41-4D",
      coordinates: [10, 1220],
      render: CustomRender,
    },
    {
      id: "42-4D",
      content: "42-4D",
      coordinates: [110, 1220],
      render: CustomRender,
    },
    {
      id: "49-4D",
      content: "49-4D",
      coordinates: [210, 1220],
      render: CustomRender,
    },
    {
      id: "06-5I",
      content: "06-5I",
      coordinates: [10, 1400],
      render: CustomRender,
    },
    {
      id: "09-5I",
      content: "09-5I",
      coordinates: [110, 1400],
      render: CustomRender,
    },
    {
      id: "26-5R",
      content: "26-5R",
      coordinates: [210, 1400],
      render: CustomRender,
    },
    {
      id: "32-5I",
      content: "32-5I",
      coordinates: [10, 1440],
      render: CustomRender,
    },
    {
      id: "36-5I",
      content: "36-5I",
      coordinates: [110, 1440],
      render: CustomRender,
    },
    {
      id: "37-5R",
      content: "37-5R",
      coordinates: [210, 1440],
      render: CustomRender,
    },
    {
      id: "45-5I",
      content: "45-5I",
      coordinates: [10, 1480],
      render: CustomRender,
    },
  ],
  links: [
    { input: "root", output: "1" },
    { input: "root", output: "2" },
    { input: "root", output: "3" },
    { input: "root", output: "4" },
    { input: "root", output: "5" },
    { input: "1", output: "01-1I" },
    { input: "1", output: "05-1R" },
    { input: "1", output: "07-1I" },
    { input: "1", output: "15-1R" },
    { input: "1", output: "18-1R" },
    { input: "1", output: "19-1P" },
    { input: "1", output: "23-1R" },
    { input: "1", output: "25-1R" },
    { input: "1", output: "27-1R" },
    { input: "1", output: "29-1R" },
    { input: "1", output: "30-1P" },
    { input: "1", output: "33-1R" },
    { input: "1", output: "38-1R" },
    { input: "1", output: "39-1I" },
    { input: "1", output: "44-1P" },
    { input: "2", output: "02-2I" },
    { input: "2", output: "12-2R" },
    { input: "2", output: "13-2I" },
    { input: "2", output: "14-2P" },
    { input: "2", output: "20-2R" },
    { input: "2", output: "24-2R" },
    { input: "2", output: "28-2R" },
    { input: "2", output: "31-2R" },
    { input: "2", output: "50-2I" },
    { input: "3", output: "08-3I" },
    { input: "3", output: "16-3D" },
    { input: "3", output: "17-3D" },
    { input: "3", output: "43-3P" },
    { input: "3", output: "46-3P" },
    { input: "3", output: "47-3R" },
    { input: "3", output: "48-3I" },
    { input: "4", output: "03-4R" },
    { input: "4", output: "04-4R" },
    { input: "4", output: "10-4I" },
    { input: "4", output: "11-4R" },
    { input: "4", output: "21-4I" },
    { input: "4", output: "22-4D" },
    { input: "4", output: "34-4D" },
    { input: "4", output: "35-4D" },
    { input: "4", output: "40-4P" },
    { input: "4", output: "41-4D" },
    { input: "4", output: "42-4D" },
    { input: "4", output: "49-4D" },
    { input: "5", output: "06-5I" },
    { input: "5", output: "09-5I" },
    { input: "5", output: "26-5R" },
    { input: "5", output: "32-5I" },
    { input: "5", output: "36-5I" },
    { input: "5", output: "37-5R" },
    { input: "5", output: "45-5I" },
  ],
};
