/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7tQibiuZkZd
 */
'use client'


export function Chatbot() {

  return (
    <>
      <div className="bg-white text-black p-1 text-center rounded-md absolute bottom-0 left-0 pointer drop-shadow-lg">
        <span className="material-symbols-outlined text-4xl text-center">
          person_raised_hand
        </span>
      </div>
    </>
  )
}
